name: CI

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
        pip install pipenv
        python -m pipenv install --dev
        cp tests/config.ini src
    - name: Run tests
      run: |
          cd /home/runner/work/simple-v2ray-gfwlist/simple-v2ray-gfwlist
          python -m pipenv run pytest -v
