name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
      pip install pipenv
      pipenv install --dev
    - name: Run tests
      run: pipenv run pytest -v
