name: CI

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
        pip3 install pipenv
        python3 -m pipenv install --dev
        cp tests/config.ini src
    - name: Run tests
      run: |
          python3 -m pipenv run pytest -v
